spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/MALL_PMS?serverTimezone=GMT%2B8
    username: root
    password: '0810'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
logging:
  level:
    com.sxx: debug
feign:
  httpclient:
    connection-timeout: 10000
