spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/MALL_PMS?serverTimezone=GMT%2B8
    username: root
    password: '0810'
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.sxx: debug