spring:
  cloud:
    gateway:
      routes:
        - id: thirdparty_route
          uri: lb://third-party
          predicates:
          - Path=/api/thirdparty/**
          filters:
          - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: member_route
          uri: lb://member
          predicates:
          - Path=/api/member/**
          filters:
          - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: product_route
          uri: lb://product
          predicates:
          - Path=/api/product/**
          filters:
          - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://admin
          predicates:
          - Path=/api/**
          filters:
          - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gateway
server:
  port: 88